### ISSUE TITLE
Support Google Cloud Container Registry credential helper

### ISSUE THREAD

**Issue by tjacoby** [charleskorn/batect#103]
Pulling images from the Google Cloud Container registry fails with the following error:

```
Could not build image: The credentials returned for 'eu.gcr.io' by the credential helper executable 'docker-credential-gcloud' are invalid: there is no 'ServerURL' field.
```

The reason seems to be because the Username reported by the credential helper is `_dcgcloud_token` instead of the expected `<token>`.

This is the extract from the batect log file (replaced the actual secret with "xxx"):
```json
{
    "@timestamp": "2019-05-22T14:50:35.754Z",
    "@message": "Process exited.",
    "@severity": "debug",
    "@source": "batect.os.ProcessRunner",
    "@processId": 14167,
    "@threadId": 14,
    "@threadName": "pool-1-thread-1",
    "output": "{\n  \"Secret\": \"xxx\",\n  \"Username\": \"_dcgcloud_token\"\n}\n",
    "exitCode": 0,
    "command": [
        "docker-credential-gcloud",
        "get"
    ]
}
```

**Comment by charleskorn** [comment]
Hey @tjacoby, thanks for taking the time to report this issue. Looks like the GCP credential helper isn't quite meeting [the requirements of a credential helper](https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol) and this is breaking things. This is a relatively easy thing to workaround though, so I'll take a look and push out a fix shortly.

**Comment by charleskorn** [comment]
I've just pushed a fix for this and it should be part of the next release. Thanks again @tjacoby!

**Comment by tjacoby** [comment]
Hi Charles,

thanks for picking up my request so quickly. I built batect locally from master and tried the fix but unfortunately it still doesn't work. 

It fails with the following error now:
```
build-env: building image: step 1 of 17: FROM eu.gcr.io/xxx-xxx-xxx/conda:814a9e1654ac16c661ba60f78e81782c26eadf3d

Error: Could not build image from directory '/home/xxx/xxx/xxx/gcp_xxx/docker'.
Building image failed: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication. Output from build process was:
Step 1/17 : FROM eu.gcr.io/xxx-xxx-xxx/conda:814a9e1654ac16c661ba60f78e81782c26eadf3d
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

I saw that you are using a `PasswordDockerRegistryCredentials` for the Google container registry. I tried changing the code to use `TokenDockerRegistryCredentials` but this still does not fix the issue (and causes the same error message as above).

Does the documentation from Google provide some more hints for you? https://cloud.google.com/container-registry/docs/advanced-authentication

Building the docker file manually from the terminal via `docker build . ` works without issues.

**Comment by charleskorn** [comment]
I tried it with pulling an image directly it was working for me - are you able to try pulling an image directly and see if that works for you?

So instead of `build_directory: ...`, use `image: eu.gcr.io/xxx-xxx-xxx/conda:814a9e1654ac16c661ba60f78e81782c26eadf3d`

**Comment by tjacoby** [comment]
Yes - pulling the image works

**Comment by charleskorn** [comment]
OK, looks like there's an issue with building images - I'll take a look.

**Comment by charleskorn** [comment]
I've fixed the issue building images as well, and this will be part of the next release. 

If you want to use a version with this fix in the meantime, https://bintray.com/charleskorn/batect/batect should have a pre-release version available with this fix in the next 20 minutes or so.

Thanks again for your feedback @tjacoby!
